package com.example.bandsignalinfo.ui.theme

import androidx.compose.ui.graphics.Color

// T-Mobile — Magenta
val TMobileLight = Color(0xFFE20074)
val TMobileLightOn = Color(0xFFFFFFFF)
val TMobileLightContainer = Color(0xFFFFD8EE)
val TMobileLightOnContainer = Color(0xFF3E0022)
val TMobileLightSecondary = Color(0xFF9C4070)
val TMobileLightSecondaryContainer = Color(0xFFFFD8EC)
val TMobileLightOnSecondaryContainer = Color(0xFF3A071E)
val TMobileLightSurfaceVariant = Color(0xFFFFF0F7)

val TMobileDark = Color(0xFFFFB1CD)
val TMobileDarkOn = Color(0xFF6C0035)
val TMobileDarkContainer = Color(0xFF96004F)
val TMobileDarkOnContainer = Color(0xFFFFD8EE)
val TMobileDarkSecondary = Color(0xFFFFB1D5)
val TMobileDarkSecondaryContainer = Color(0xFF7A1A45)
val TMobileDarkOnSecondaryContainer = Color(0xFFFFD8EC)
val TMobileDarkSurfaceVariant = Color(0xFF4A1530)

// AT&T — Blue
val ATTLight = Color(0xFF009FDB)
val ATTLightOn = Color(0xFFFFFFFF)
val ATTLightContainer = Color(0xFFC8EEFF)
val ATTLightOnContainer = Color(0xFF001F2A)
val ATTLightSecondary = Color(0xFF406C80)
val ATTLightSecondaryContainer = Color(0xFFDCF2FF)
val ATTLightOnSecondaryContainer = Color(0xFF001F2A)
val ATTLightSurfaceVariant = Color(0xFFF0F9FF)

val ATTDark = Color(0xFF77D5F7)
val ATTDarkOn = Color(0xFF003547)
val ATTDarkContainer = Color(0xFF004D66)
val ATTDarkOnContainer = Color(0xFFC8EEFF)
val ATTDarkSecondary = Color(0xFF77C8E0)
val ATTDarkSecondaryContainer = Color(0xFF1A4A5C)
val ATTDarkOnSecondaryContainer = Color(0xFFDCF2FF)
val ATTDarkSurfaceVariant = Color(0xFF0A2535)

// Verizon — Red
val VerizonLight = Color(0xFFCD040B)
val VerizonLightOn = Color(0xFFFFFFFF)
val VerizonLightContainer = Color(0xFFFFDAD6)
val VerizonLightOnContainer = Color(0xFF410002)
val VerizonLightSecondary = Color(0xFF904040)
val VerizonLightSecondaryContainer = Color(0xFFFFEDEB)
val VerizonLightOnSecondaryContainer = Color(0xFF410002)
val VerizonLightSurfaceVariant = Color(0xFFFFF0EF)

val VerizonDark = Color(0xFFFFB3AE)
val VerizonDarkOn = Color(0xFF680003)
val VerizonDarkContainer = Color(0xFF930006)
val VerizonDarkOnContainer = Color(0xFFFFDAD6)
val VerizonDarkSecondary = Color(0xFFFFB3AE)
val VerizonDarkSecondaryContainer = Color(0xFF6B1515)
val VerizonDarkOnSecondaryContainer = Color(0xFFFFEDEB)
val VerizonDarkSurfaceVariant = Color(0xFF4A1015)

// Default — Blue (matches app icon background)
val DefaultLight = Color(0xFF1565C0)
val DefaultLightOn = Color(0xFFFFFFFF)
val DefaultLightContainer = Color(0xFFD6E4FF)
val DefaultLightOnContainer = Color(0xFF001A41)
val DefaultLightSecondary = Color(0xFF415F91)
val DefaultLightSecondaryContainer = Color(0xFFD8E2FF)
val DefaultLightOnSecondaryContainer = Color(0xFF001A41)
val DefaultLightSurfaceVariant = Color(0xFFF0F4FF)

val DefaultDark = Color(0xFFA8C7FA)
val DefaultDarkOn = Color(0xFF003062)
val DefaultDarkContainer = Color(0xFF1A4A8C)
val DefaultDarkOnContainer = Color(0xFFD6E4FF)
val DefaultDarkSecondary = Color(0xFFADC6FF)
val DefaultDarkSecondaryContainer = Color(0xFF284777)
val DefaultDarkOnSecondaryContainer = Color(0xFFD8E2FF)
val DefaultDarkSurfaceVariant = Color(0xFF1A2035)
